use std::env;
use std::fs::File;
use std::io::{BufRead, BufReader};
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=data/harmonized-system.csv");

    let csv_path = Path::new("data/harmonized-system.csv");
    let file = File::open(csv_path).expect("Failed to open data/harmonized-system.csv");
    let reader = BufReader::new(file);
    let mut lines = reader.lines();

    // 跳过标题行
    let _header = lines.next().unwrap().unwrap();

    let mut entries = Vec::new();
    for line in lines {
        let line = line.unwrap();
        let parts: Vec<&str> = line.split(',').collect();
        if parts.len() >= 3 {
            let hs_code = parts[1].trim_matches('"').to_string();
            let desc = parts[2].trim_matches('"').to_string();
            entries.push((hs_code, desc));
        }
    }

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("hs_data.rs");

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs from harmonized-system.csv\n");
    code.push_str("use phf::phf_map;\n\n");
    code.push_str("pub static HS_MAP: phf::Map<&'static str, &'static str> = phf_map! {\n");

    for (hs_code, desc) in &entries {
        // ✅ 改名了
        let escaped_desc = desc.replace('\\', "\\\\").replace('"', "\\\"");
        code.push_str(&format!("    \"{}\" => \"{}\",\n", hs_code, escaped_desc));
    }
    code.push_str("};\n");

    std::fs::write(&dest_path, code).unwrap();
    println!(
        "cargo:info=Generated hs_data.rs with {} entries",
        entries.len()
    );
}
